server:
  port: 8089
  servlet:
    context-path: /test
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  signerKey: "S9IE4URbeTkCrr1XP8jWEvvo4DqmcHLxckR3m7l4B6BssDB9uEcIG9xoYouVeLxT3udFeOSQfHRDsKMeuUS35j"